# Generated by Django 5.2.5 on 2025-09-06 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_tensecondcpsscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpsscore',
            name='duration',
        ),
    ]
