# Generated by Django 5.2.5 on 2025-09-06 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_cpsscore_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twosecondscore',
            options={'ordering': ['-score']},
        ),
    ]
