# Generated by Django 5.2.5 on 2025-09-08 16:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_spacebarscore10'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TwentySecondSpacebarScore',
            new_name='SpacebarScore20',
        ),
    ]
